#  Arithmetic and Variable Assignment

In [1]:
import numpy as np

In [2]:
1+1

2

In [3]:
3*7

21

In [4]:
7/3

2.3333333333333335

In [5]:
2**3

8

In [6]:
np.exp(2)

7.38905609893065

In [7]:
np.log(2)

0.6931471805599453

In [8]:
np.sqrt(5)

2.23606797749979

In [9]:
np.pi

3.141592653589793

In [10]:
pi = 3.141592653589793

In [11]:
pi

3.141592653589793

In [12]:
x = np.sqrt(2)

In [13]:
print(x)

1.4142135623730951


In [17]:
# Valid variable names
height = 5.9
user_age = 25
total_students = 100
my_variable_1 = "Hello"

# Invalid variable names
#2nd_attempt = "Invalid"  # Starts with a digit
#user-age = 30  # Contains invalid character "-"
#for = 5  # Uses a reserved keyword

### Vectors and matrices

In [18]:
# Using a list to represent a vector
vector_list = [2.0, 4.5, 1.3, 7.0]
words_list = ['red', 'blue', 'green']

# Accessing elements
print("Vector using list:", vector_list)
print("First element:", vector_list[0])
print("Second element:", vector_list[1])

Vector using list: [2.0, 4.5, 1.3, 7.0]
First element: 2.0
Second element: 4.5


In [19]:
# Using a NumPy array to represent a vector
# Creating a NumPy array from a list
vector_np = np.array([2.0, 4.5, 1.3, 7.0])

# Accessing elements
print("Vector using NumPy array:", vector_np)
print("First element:", vector_np[0])
print("Second element:", vector_np[1])

Vector using NumPy array: [2.  4.5 1.3 7. ]
First element: 2.0
Second element: 4.5


In [28]:
# Creating a NumPy array of zeros
v1 = np.zeros((3,2))

In [30]:
print(v1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
v2 = np.zeros(2)
print(v2)

[0. 0.]


In [46]:
v2[1] = 3

In [47]:
v2

array([0., 3.])

In [38]:
# access the length of v2 (works for vectors)
len(v2)

2

In [29]:
# access the shape (shape is tuple)
v1.shape, v2.shape

((3, 2), (2,))

In [31]:
# Creating a NumPy array of ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Creating a NumPy array with evenly spaced values
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [36]:
# Creating a NumPy array with a range of values
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Creating a NumPy array with random values
A = np.random.rand(3, 3)

In [45]:
A

array([[0.44483945, 0.7481015 , 0.15211825],
       [0.68020426, 0.0293645 , 0.5       ],
       [0.05320141, 0.84086561, 0.93319232]])

In [ ]:
# How to create a random number between 3 and 4?

In [44]:
A[1,2] = 0.5

In [48]:
primes = np.arange(1,6)
primes

array([1, 2, 3, 4, 5])

In [49]:
primes**(1/2) # acts component-wise

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [50]:
primes * primes # dot product

array([ 1,  4,  9, 16, 25])

In [ ]:
primes[0], primes[2]

In [51]:
# You can do many things with indexes:
primes[2:4]

array([3, 4])

In [53]:
primes[-2] # second element from the end

4

In [54]:
primes[[3,1]]

array([4, 2])

In [55]:
primes >3

array([False, False, False,  True,  True])

In [56]:
index = [0,1]

In [57]:
primes[index]

array([1, 2])

### Exercises